PDMS.Web/Controllers/OEE/OEEController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using OfficeOpenXml;
using PDMS.Common.Helpers;
using PDMS.Core;
using PDMS.Core.BaseController;
using PDMS.Model;
using PDMS.Model.EntityDTO;
using PDMS.Model.ViewModels;
using OfficeOpenXml.Style;
using System.Drawing;
using PDMS.Common.Constants;
using PDMS.Common;
using System.Text.RegularExpressions;
using OfficeOpenXml.Drawing.Chart;
using OfficeOpenXml.Drawing;

namespace PDMS.Web.Controllers
{
    public class OEEController : WebControllerBase
    {

        /// <summary>
        /// 获取当前登陆人的厂区ID
        /// </summary>
        /// <returns></returns>
        public int GetPlantOrgUid()
        {
            int plantorguid = 0;
            if (CurrentUser.GetUserInfo.OrgInfo != null && CurrentUser.GetUserInfo.OrgInfo.Count > 0 && CurrentUser.GetUserInfo.OrgInfo[0].Plant_OrganizationUID != null)
                plantorguid = (int)CurrentUser.GetUserInfo.OrgInfo[0].Plant_OrganizationUID;
            return plantorguid;
        }
        #region   -----OEE_MachineInfo  Create By WenFan -------
        public ActionResult OEE_MachineInfo()
        {
            Fixture_DefectCodeVM currentVM = new Fixture_DefectCodeVM();
            int optypeID = 0;
            int funPlantID = 0;
            if (CurrentUser.GetUserInfo.OrgInfo != null && CurrentUser.GetUserInfo.OrgInfo.Count > 0 && CurrentUser.GetUserInfo.OrgInfo[0].Plant != null && CurrentUser.GetUserInfo.OrgInfo[0].Plant_OrganizationUID != null)
            {
                if (CurrentUser.GetUserInfo.OrgInfo[0].OPType_OrganizationUID != null)
                {
                    optypeID = CurrentUser.GetUserInfo.OrgInfo[0].OPType_OrganizationUID.Value;
                }

                if (CurrentUser.GetUserInfo.OrgInfo[0].Funplant_OrganizationUID != null)
                {
                    funPlantID = CurrentUser.GetUserInfo.OrgInfo[0].Funplant_OrganizationUID.Value;
                }
                currentVM.Plants = new List<PlantVM>() { new PlantVM() { Plant = CurrentUser.GetUserInfo.OrgInfo[0].Plant, Plant_OrganizationUID = CurrentUser.GetUserInfo.OrgInfo[0].Plant_OrganizationUID.Value } };
            }
            else
            {
                //获取
                var Plants = new List<PlantVM>();
                var apiUrl = string.Format("Settings/GetPlantsAPI?PlantOrgUid={0}", 0);
                var responMessage = APIHelper.APIGetAsync(apiUrl);
                var result = responMessage.Content.ReadAsStringAsync().Result;
                var systemOrgDTOs = JsonConvert.DeserializeObject<List<SystemOrgDTO>>(result);
                foreach (var item in systemOrgDTOs)
                {
                    PlantVM plantvm = new PlantVM() { Plant = item.Organization_Name, Plant_OrganizationUID = item.Organization_UID };
                    Plants.Add(plantvm);
                }
                currentVM.Plants = Plants;
            }
            currentVM.OptypeID = optypeID;
            currentVM.FunPlantID = funPlantID;
            //ViewBag.PageTitle = "异常原因维护";
            return View("OEE_MachineInfo", currentVM);
        }

        public ActionResult QueryOEE_MachineInfo(OEE_MachineInfoDTO serchModel, Page page)
        {
            string json = JsonConvert.SerializeObject(serchModel);
            var apiUrl = string.Format("OEE/QueryOEE_MachineInfoAPI");
            HttpResponseMessage responMessage = APIHelper.APIPostAsync(serchModel, page, apiUrl);
            var result = responMessage.Content.ReadAsStringAsync().Result;
            return Content(result, "application/json");
        }

        public ActionResult AddOEE_Machine(OEE_MachineInfoDTO serchModel)
        {
            serchModel.Modify_UID = this.CurrentUser.AccountUId;
            serchModel.Modify_Date = DateTime.Now;
            string json = JsonConvert.SerializeObject(serchModel);
            var apiUrl = string.Format("OEE/AddOEE_MachineAPI");
            HttpResponseMessage responMessage = APIHelper.APIPostAsync(json, apiUrl);
            var result = responMessage.Content.ReadAsStringAsync().Result;
            return Content(result, "application/json");
        }

        public ActionResult ExportOEE_MachineByQuery(OEE_MachineInfoDTO serchModel)
        {
            string json = JsonConvert.SerializeObject(serchModel);
            var apiUrl = string.Format("OEE/ExportOEE_MachineByQueryAPI");
            HttpResponseMessage responMessage = APIHelper.APIPostAsync(json, apiUrl);
            var result = responMessage.Content.ReadAsStringAsync().Result;
            var list = JsonConvert.DeserializeObject<List<OEE_MachineInfoDTO>>(result).ToList();
            var stream = new MemoryStream();
            var fileName = PathHelper.SetGridExportExcelName("OEE_MachineReport");
            var stringHeads = GetOEE_MachineByHead();
            using (var excelPackage = new ExcelPackage(stream))
            {
                var worksheet = excelPackage.Workbook.Worksheets.Add("OEE_MachineReport");
                for (int colIndex = 0; colIndex < stringHeads.Length; colIndex++)
                {
                    worksheet.Cells[1, colIndex + 1].Value = stringHeads[colIndex];
                }

                for (int index = 0; index < list.Count; index++)
                {
                    var currentRecord = list[index];
                    worksheet.Cells[index + 2, 1].Value = index + 1;//序号
                    worksheet.Cells[index + 2, 2].Value = currentRecord.Plant_Organization_Name;//厂区
                    worksheet.Cells[index + 2, 3].Value = currentRecord.BG_Organization_Name;//BG
                    worksheet.Cells[index + 2, 4].Value = currentRecord.FunPlant_Organization_Name;//功能厂
                    worksheet.Cells[index + 2, 5].Value = currentRecord.Project_Name;//制程
                    worksheet.Cells[index + 2, 6].Value = currentRecord.Line_Name;
                    worksheet.Cells[index + 2, 7].Value = currentRecord.Station_Name;
                    worksheet.Cells[index + 2, 8].Value = currentRecord.EQP_EMTSerialNum;
                    worksheet.Cells[index + 2, 9].Value = currentRecord.MachineNo;
                    worksheet.Cells[index + 2, 10].Value = currentRecord.Is_Enable ? "启用" : "禁用";
                    worksheet.Cells[index + 2, 11].Value = currentRecord.Modify_Name;
                    worksheet.Cells[index + 2, 12].Value = currentRecord.Modify_Date.ToString("yyyy-MM-dd HH:mm");
                }
                worksheet.Cells.AutoFitColumns();
                excelPackage.Save();
            }

            return new FileContentResult(stream.ToArray(), "application/octet-stream")
            { FileDownloadName = Server.UrlEncode(fileName) };
        }

        public ActionResult ExportOEE_Machine(string uids)
        {
            var apiUrl = string.Format("OEE/ExportOEE_MachineAPI?uids={0}", uids);
            HttpResponseMessage responMessage = APIHelper.APIGetAsync(apiUrl);
            var result = responMessage.Content.ReadAsStringAsync().Result;
            var list = JsonConvert.DeserializeObject<List<OEE_MachineInfoDTO>>(result).ToList();
            var stream = new MemoryStream();
            var fileName = PathHelper.SetGridExportExcelName("OEE_MachineReport");
            var stringHeads = GetOEE_MachineByHead();
            using (var excelPackage = new ExcelPackage(stream))
            {
                var worksheet = excelPackage.Workbook.Worksheets.Add("OEE_MachineReport");
                for (int colIndex = 0; colIndex < stringHeads.Length; colIndex++)
                {
                    worksheet.Cells[1, colIndex + 1].Value = stringHeads[colIndex];
                }

                for (int index = 0; index < list.Count; index++)
                {
                    var currentRecord = list[index];
                    worksheet.Cells[index + 2, 1].Value = index + 1;//序号
                    worksheet.Cells[index + 2, 2].Value = currentRecord.Plant_Organization_Name;//厂区
                    worksheet.Cells[index + 2, 3].Value = currentRecord.BG_Organization_Name;//BG
                    worksheet.Cells[index + 2, 4].Value = currentRecord.FunPlant_Organization_Name;//功能厂
                    worksheet.Cells[index + 2, 5].Value = currentRecord.Project_Name;//制程
                    worksheet.Cells[index + 2, 6].Value = currentRecord.Line_Name;
                    worksheet.Cells[index + 2, 7].Value = currentRecord.Station_Name;
                    worksheet.Cells[index + 2, 8].Value = currentRecord.EQP_EMTSerialNum;
                    worksheet.Cells[index + 2, 9].Value = currentRecord.MachineNo;
                    worksheet.Cells[index + 2, 10].Value = currentRecord.Is_Enable ? "启用" : "禁用";
                    worksheet.Cells[index + 2, 11].Value = currentRecord.Modify_Name;
                    worksheet.Cells[index + 2, 12].Value = currentRecord.Modify_Date.ToString("yyyy-MM-dd HH:mm");
                }
                worksheet.Cells.AutoFitColumns();
                excelPackage.Save();
            }

            return new FileContentResult(stream.ToArray(), "application/octet-stream")
            { FileDownloadName = Server.UrlEncode(fileName) };
        }

        public ActionResult UpdateOEE_Machine(OEE_MachineInfoDTO serchModel)
        {
            serchModel.Modify_UID = this.CurrentUser.AccountUId;
            serchModel.Modify_Date = DateTime.Now;
            string json = JsonConvert.SerializeObject(serchModel);
            var apiUrl = string.Format("OEE/UpdateOEE_MachineAPI");
            HttpResponseMessage responMessage = APIHelper.APIPostAsync(json, apiUrl);
            var result = responMessage.Content.ReadAsStringAsync().Result;
            return Content(result, "application/json");
        }

        public ActionResult GetOEE_MachineInfoByUID(string uid)
        {

PDMS.Web/Views/OEE/StationDataMaintence.cshtml
@{
}

@{

    ViewBag.Edit = T("Common.Edit").Text;
}
<section class="content portal-content">
    <div class="row">
        @*<div class="col-lg-12">
            <section class="content-header portal-content-header">
                <h1>@T("OEE.StationDataMaintence")</h1>
            </section>
        </div>*@
        <hr style="margin: 0px; height: 1px; border: 0px; background-color: #D5D5D5; color: #D5D5D5;" />
        <div class="col-md-12 col-lg-9">
            <h4 class="margin-td-5" id="js_search_keywords"></h4>
        </div>

    </div>
    <hr class="hr-custom">
    <div class="row">
        <div class="col-md-12 table-container">
            <table class="table table-striped table-hover table-condensed nowrap" id="js_OEE_Station_datatable">
                <thead>
                    <tr id="js_rpt_tr">
                        <th class="table-col-checkbox nosort">
                            <input type="checkbox" class="js-checkbox-all" />
                        </th>
                        <th class="table-col-action nosort">@T("Common.Action")</th>
                        <th class="table-col-seq nosort">@T("Common.Seq")</th>
                        <th>@T("QA.Project")</th>
                        <th>@T("OEE.Line")</th>
                        <th>@T("ME.Process_Station")</th>
                        <th>@T("OEE.MachineName")</th>
                        <th>@T("QA.Timeperiod")</th>
                        <th>@T("OEE.IsSubmit") </th>
                         <th>@T("QA.Editor")</th>
                        <th>@T("QA.Changetime")</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr id="js_rpt_tr_foot">
                        <th class="table-col-checkbox nosort">
                            <input type="checkbox" class="js-checkbox-all" />
                        </th>
                        <th class="table-col-action nosort">@T("Common.Action")</th>
                        <th class="table-col-seq nosort">@T("Common.Seq")</th>
                        <th>@T("QA.Project")</th>
                        <th>@T("OEE.Line")</th>
                        <th>@T("ME.Process_Station")</th>
                        <th>@T("OEE.MachineName")</th>
                        <th>@T("QA.Timeperiod")</th>
                        <th>@T("OEE.IsSubmit") </th>
                        <th>@T("QA.Editor")</th>
                        <th>@T("QA.Changetime")</th>
                    </tr>
                </tfoot>
            </table>
            <div id="page" class="row"></div>

        </div><!--/表格-->

    </div><!-- / 內容 表格列 -->
</section>

@section ViewScripts{
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap-select.css" />
    <script type="text/javascript" src="~/Scripts/EQP/bootstrap-select.js"></script>
    <script type="text/javascript">

        $(function () {
            var OEE_StationDataMaintenance = (function () {
                var urls = {
                    QueryStationDataMaintence: '@Html.Raw(Url.Action("QueryStationDataMaintence", "OEE"))',
                    QueryStationNameList: '@Html.Raw(Url.Action("QueryStationNameList", "OEE"))',
                };

                Date.prototype.Format = function (fmt) { //author: meizz
                    var o = {
                        "M+": this.getMonth() + 1, //月份
                        "d+": this.getDate(), //日
                        "h+": this.getHours(), //小时
                        "m+": this.getMinutes(), //分
                        "s+": this.getSeconds(), //秒
                        "q+": Math.floor((this.getMonth() + 3) / 3), //季度
                        "S": this.getMilliseconds() //毫秒
                    };
                    if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
                    for (var k in o)
                        if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
                    return fmt;
                }
                var columns = [
                 {
                     createdCell: function (td, cellData, rowData, row, col) {
                         $(td).html('<input type="checkbox" name="cktrans" class="js-checkbox-item" value="' + rowData.OEE_MachineInfo_UID + '">')
                              .addClass('table-col-checkbox');
                     },
                     className: "text-center"
                 },
                 {
                     createdCell: function (td, cellData, rowData, row, col) {
                         var hiddenHtml = '<input type="hidden"  name="Plant_Organization_UID" value=' + rowData.Plant_Organization_UID + '>'
                             + '<input type="hidden" name="BG_Organization_UID" value="' + rowData.BG_Organization_UID + '">'
                             + '<input type="hidden" name="EQP_Uid" value="' + rowData.EQP_Uid + '">'
                             + '<input type="hidden" name="LineID" value="' + rowData.LineID + '">'
                                + '<input type="hidden" name="Project_UID" value="' + rowData.Project_UID + '">'
                             + '<input type="hidden" name="StationID" value="' + rowData.StationID + '">'
                             + '<input type="hidden" name="MachineName" value="' + rowData.MachineNo + '">'
                             + '<input type="hidden" name="FunPlant_Organization_UID" value="' + rowData.FunPlant_Organization_UID + '">';
                         var buttonHtml = '<button type="button" class="btn btn-primary btn-xs js-grid-edit" data-id="' + rowData.OEE_MachineInfo_UID + '">@ViewBag.Edit</button>'
                        
                        var  MachineNo = rowData.MachineNo.replace(/\%/g, "%25").replace(/\#/g, "%23").replace(/\&/g, "%26").replace(/\+/g, "%2B");
                        var renderHtml = '<a href="DefectCodeMaintence?MachineInfo_UID=' + rowData.OEE_MachineInfo_UID + "&Plant_UID=" + rowData.Plant_Organization_UID + "&BG_UID=" + rowData.BG_Organization_UID + "&Fun_UID=" + rowData.FunPlant_Organization_UID + "&EQP_Uid=" + rowData.EQP_Uid + "&MachineName=" + MachineNo + "&LineID=" + rowData.LineID + "&StationID=" + rowData.StationID + "&Project_UID=" + rowData.Project_UID + '">' + buttonHtml + '<a>';
                         $(td).html(renderHtml);
                     },
                     className: "text-center"
                 }, {
                     data: null,
                     className: "table-col-seq"
                 }, {
                     data: "Project_Name",
                     className: "min-col-xs"
                 }, {
                     data: "Line_Name",
                     className: "min-col-xs"
                 },
                  {
                      data: "Station_Name",
                      className: "min-col-xs"
                  },
                  {
                      data: "MachineNo",
                      className: "min-col-xs"
                  },
                   {
                       data: "TimeInterval",
                       className: "min-col-xs"
                   },
                    {
                        data: "IsSubmit",
                        className: "min-col-xs"
                    },
                   {
                       data: "Modify_Name",
                       className: "min-col-lg"
                   }, {
                       data: null,
                       createdCell: function (td, cellData, rowData, row, col) {
                           if (new Date(rowData.Modify_Date) < new Date("0001-01-02")) {
                               $(td).html("");
                           } else {
                               $(td).html(new Date(rowData.Modify_Date).Format("yyyy-MM-dd hh:mm"));
                           }
                       },
                       className: "min-col-xs"
                   }
                ];
                var _getParams = function () {
                    return $('#js_form_query').serialize().replace(/\+/g, " ");
                };
                var _queryOEE_StationDataMaintenance = function (firstLoad) {
                    var config = {
                        pageId: "#page",
                        tableId: "#js_OEE_Station_datatable",
                        remoteUrl: urls.QueryStationDataMaintence,
                        searchParams: _getParams(),
                        tableOptions: {
                            scrollX: true,
                            autoWidth: true,
                            columns: columns
                        }
                    };

                    if (!firstLoad) {
                        $('#page').page('destroy');
                        PDMS.Utility.Criteria.Build();
                    }

                    PDMS.Utility.Pages.Set(config);
                };
                return {
                    urls: urls,
                    Init: function () {
                        _queryOEE_StationDataMaintenance(true);
                    },
                    QueryStuffs: function () {
                        _queryOEE_StationDataMaintenance(false);
                    },
                }
            })();
            OEE_StationDataMaintenance.Init();

            ////显示修改的界面
            //$('body').on('click', '.js-grid-edit', function () {
            //    $('#js_StationList_modal').modal('show', $(this));
            //});

            @*$('body').on('click', '.js-grid-edit', function () {
                var Plant_UID1 = $(this).find("input[name='Plant_Organization_UID']").val();
                var Plant_UID = $("input[name='Plant_Organization_UID']").val();
                var BG_UID = $("input[name='BG_Organization_UID']").val();
                var Fun_UID = $("input[name='FunPlant_Organization_UID']").val();
                var EQP_Uid = $("input[name='EQP_Uid']").val();
                var LineID = $("input[name='LineID']").val();
                var StationID = $("input[name='StationID']").val();
                var Project_UID = $("input[name='Project_UID']").val();
                var MachineName = $("input[name='MachineName']").val();
                var id = $(this).attr('data-id'),
                    url = '@Url.Action("DefectCodeMaintence", "OEE")';
                window.location.href = url + "?MachineInfo_UID=" + id + "&&Plant_UID=" + Plant_UID + "&&BG_UID=" + BG_UID + "&&Fun_UID=" + Fun_UID + "&&EQP_Uid=" + EQP_Uid + "&&MachineName=" + MachineName + "&&LineID=" + LineID + "&&StationID=" + StationID + "&&Project_UID=" + Project_UID;
            });*@
        });
    </script>
} 