PDMS.Web/Controllers/EQPBoardController.cs
using Newtonsoft.Json;
using OfficeOpenXml;
using PDMS.Common.Constants;
using PDMS.Common.Helpers;
using PDMS.Core;
using PDMS.Core.BaseController;
using PDMS.Model;
using PDMS.Model.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Web.Mvc;
using PDMS.Model.ViewModels.Settings;
using System.Web.Helpers;
using System.Net;
using System.Web.Script.Serialization;
using PDMS.Core.Authentication;
using PDMS.Core.Filters;
using System.Web;
using System.Web.SessionState;
using PDMS.Model.EntityDTO;

namespace PDMS.Web.Controllers
{
    public class EQPBoardController : WebControllerBase
    {
        public int GetPlantOrgUid()
        {
            int plantorguid = 0;
            if (CurrentUser.GetUserInfo.OrgInfo != null && CurrentUser.GetUserInfo.OrgInfo.Count > 0 && CurrentUser.GetUserInfo.OrgInfo[0].Plant_OrganizationUID != null)
                plantorguid = (int)CurrentUser.GetUserInfo.OrgInfo[0].Plant_OrganizationUID;
            return plantorguid;
        }
        // GET: EQPBoard
        public ActionResult Index()
        {

            int Plant_Organization_UID= GetPlantOrgUid();
            EQPRepairVM currentVM = new EQPRepairVM();
            var apiUrl =string.Format(@"Equipmentmaintenance/GetEQPLocationAPI?Plant_Organization_UID={0}", Plant_Organization_UID);
            var responMessage = APIHelper.APIGetAsync(apiUrl);
            var result = responMessage.Content.ReadAsStringAsync().Result;
            var eqplocation = JsonConvert.DeserializeObject<List<string>>(result);
            currentVM.eqplocation = eqplocation;
            return View(currentVM);
        }

        public ActionResult EQPBoardShow(string location)
        {
            ViewBag.location = location;
            return View();
        }

        public ActionResult GetEQPBoard(EQPRepairInfoDTO search, Page page)
        {
            var apiUrl = string.Format("Equipmentmaintenance/GetEQPBoardAPI");
            HttpResponseMessage responMessage = APIHelper.APIPostAsync(search, page, apiUrl);
            var result = responMessage.Content.ReadAsStringAsync().Result;
            return Content(result, "application/json");
        }
    }
} 

PDMS.Web/Views/EQPBoard/Index.cshtml
@model PDMS.Model.ViewModels.EQPRepairVM

<section class="content portal-content">
    <style>
        .eboard-hvr-outline-out_part, .eboard-hvr-outline-out {
            font-size: x-large;
        }
    </style>
    <input type="hidden" id="user_op" value=@ViewBag.Opty />

    <div class="wrapper eboard-wrapper">
        <header class="main-header eboard-header">
            <nav class="navbar navbar-static-top">
                <div class=" container-fluid">
                    <div class="navbar-header">
                        <!-- Logo -->
                        <div class="logo" style="background:none">
                            <b>电子看板 </b>
                        </div>

                    </div>


                </div>
                <!-- /.container-fluid -->
            </nav>
        </header>
        <!-- Full Width Column -->
        <div class="content-wrapper eboard-page" style="min-height: 617px;">
            <div class="container-fluid">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <div class="row">
                        <div class="col-md-12 eboard-header-title">
                            <strong class="eboard-header-title-line ">条件设定</strong>
                        </div>
                    </div>
                    <hr class="eboard-hr margin-t-10">
                </section>

                <!-- Main content -->

                <section class="content padding-t-0">
                    <div class="row">
                        <div class="col-md-6" style="margin-top:15px;">
                            <div class="form-group">
                                <div class="col-sm-5">
                                    <label class="col-sm-5 control-label" for="js_select_eqp_location">放置位置</label>
                                    <div class="col-sm-7">
                                        <select class="selectpicker" id="js_select_eqp_location" name="EQP_Location" data-live-search="true">
                                            <option></option>
                                            @foreach (var item in Model.eqplocation)
                                            {
                                                <option>@item</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <footer class=" eboard-main-footer" style=" border:none !important;">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 text-right eboard-footer-enter">
                        <hr class="eboard-hr no-margin no-padding eboard-hr">
                        <button type="button" class="btn btn-primary btn-lg margin-t-20 eboard-hvr-shutter-out-horizontal" ; id="js_btn_save_edit_ReportBom"><i class="fa fa-check-square-o"></i>确定</button>
                    </div>

                </div>
            </div>
        </footer>
    </div>


</section><!-- /.content -->

@section ViewScripts{
<link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap-select.css" />
<script type="text/javascript" src="~/Scripts/EQP/bootstrap-select.js"></script>
    <script type="text/javascript">
        var RoleMaintenance = null;

        $(function () {


            $(document).ready(function () {
                setInterval("startRequest()", 1000);
                setInterval("startRequest1()", 3000);
            });
            function startRequest() {
                RoleMaintenance.QueryRoles();
            }
            function startRequest1() {
                $.post(RoleMaintenance.urls.getNoticeContent, { "optype": $("#user_op").val() }, function (data) {
                    if (data != "") {
                        var warningText = data;
                        $("#divMar_System_Announcement").show();
                        $("#mar_System_Announcement").html(warningText);
                    }
                });
            }

            var RoleMaintenance = (function () {
                var urls = {
                    redirectUrl: '@Url.Action("EQPBoardShow", "EQPBoard")',
                    getNoticeContent: '@Url.Action("getNoticeContent", "Board")',
                    AddNotice: '@Url.Action("AddNotice", "Board")',
                    DeleteNotice: '@Url.Action("DeleteNotice", "Board")'
                };
                var columns = [
                    {
                        data: null,
                        className: "table-col-seq"
                    },
                {
                    data:null,
                    createdCell: function (td, cellData, rowData, row, col) {
                        $(td).html('<button type="button" class="btn btn-primary btn-xs js-grid-delete" data-id="' + rowData.UID + '">删除</button>');
                    },
                    className: "text-center"
                },
               {
                   data: "Notice_Content",
                    className: "min-col-xs"
               }, {
                    data: "State",
                    className: "min-col-lg"
                }, {
                    data: "Creator_User",
                    className: "min-col-lg"
                }, {
                    data: "Creat_Time",
                    className: "min-col-lg"
                }];

                var _getParams = function () {
                    return $('#js_form_query').serialize().replace(/\+/g, " ");
                };

                var _queryRoles = function (firstLoad) {

                    var config = {
                        pageId: "#page",
                        tableId: "#js_role_datatable",
                        remoteUrl: urls.queryRoles,
                        searchParams: _getParams(),
                        tableOptions: {
                            columns: columns
                        }
                    };

                    if (!firstLoad) {
                        $('#page').page('destroy');
                        PDMS.Utility.Criteria.Build();

                    }
                    PDMS.Utility.Pages.Set(config);

                };

                return {
                    urls: urls,
                    Init: function () {
                        PDMS.Utility.Criteria.Init();
                        _queryRoles(true);
                    },
                    QueryRoles: function () {
                        _queryRoles(false);
                    }
                }

            })();

            RoleMaintenance.Init();

            $('#js_btn_query').click(function () {
                if ($("#js_form_query").valid()) {
                    RoleMaintenance.QueryRoles();
                    $('#js_search_modal').modal('hide');
                }
            });

            //保存时运行
            $("#js_btn_save_edit_ReportBom").click(function () {
                var selectValue = $('#js_select_eqp_location').val();
                if (selectValue == "")
                {
                    PDMS.Utility.MessageBox.error("请先选择放置位置");
                    return;
                }
                else
                {
                    url = RoleMaintenance.urls.redirectUrl + '?location=' + selectValue;
                    window.location.href = url;
                }

            })
            killAside();
            function killAside() {
                $(".content-wrapper").css("cssText", "margin-left:0px !important");
            }
            //clear query conditions in search modal
            $('.eboard-hvr-outline-out').click(function () {
                if ($(this).attr('style') == 'background-color:#5CACEE')
                {
                    $(this).removeAttr('style');
                    $($(this).find("div:first")).removeClass("eboard-selected");
                }
                else
                {
                    $(this).attr('style', 'background-color:#5CACEE');
                    $($(this).find("div:first")).addClass("eboard-selected");

                }

            });

            $('#js_select_eqp_location').selectpicker({ 'selectedText': 'cat' });

            $('#js_btn_clear').click(function () {
                //如果没有特殊项的Clear，直接调用Clear方法
                PDMS.Utility.Criteria.Clear();
            });
        });
    </script>
}

<style>
    .main-header {
        display: none;
    }

    .main-footer {
        display: none;
    }

    .main-sidebar {
        display: none;
    }

    .content-wrapper {
        margin-left: 0px !important;
    }
</style>