PDMS.Web/Controllers/PlayBoardController.cs
using Newtonsoft.Json;
using PDMS.Common.Constants;
using PDMS.Common.Helpers;
using PDMS.Core;
using PDMS.Core.BaseController;
using PDMS.Model;
using PDMS.Model.EntityDTO;
using PDMS.Model.ViewModels;
using PDMS.Model.ViewModels.Common;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;

namespace PDMS.Web.Controllers.PlayBoard
{
    public class PlayBoardController : WebControllerBase
    {
        public int GetPlantOrgUid()
        {
            int plantorguid = 0;
            if (CurrentUser.GetUserInfo.OrgInfo != null && CurrentUser.GetUserInfo.OrgInfo.Count > 0 && CurrentUser.GetUserInfo.OrgInfo[0].Plant_OrganizationUID != null)
                plantorguid = (int)CurrentUser.GetUserInfo.OrgInfo[0].Plant_OrganizationUID;
            return plantorguid;
        }

        /// <summary>
        /// 播放画面
        /// </summary>
        /// <param name="playUserUID"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Index(int playUserUID)
        {
            try
            {
                //自动登录
                if (CurrentUser.GetUserInfo == null)
                {
                    var resultModel = SignInWithoutPassword(playUserUID);
                    if (!resultModel.isSuccess)
                    {
                        //playUserUID 登录失败(账号不存在或不存在播放角色)，则跳转到主画面
                        return RedirectToAction("Index", "Home");
                    }
                }
                //this.Response.Clear();//这里是关键，清除在返回前已经设置好的标头信息，这样后面的跳转才不会报错
                //var cooike = System.Web.HttpContext.Current.Request.Cookies.Get(SessionConstants.PlayBoard);
                //if (cooike != null)
                //{
                //    cooike["playUserUID"] = playUserUID.ToString();
                //}
                //else
                //{
                //    var userCookie = new HttpCookie("PlayBoard");
                //    userCookie["playUserUID"] = playUserUID.ToString();
                //    userCookie.Expires.AddDays(365);
                //    //HttpContext.Response.Cookies.Add(userCookie);
                //    HttpContext.Response.SetCookie(userCookie);
                //}

            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }

            FixtureVM currentVM = new FixtureVM();
            var userUID = CurrentUser.AccountUId;
            //if (playUserUID.HasValue)
            //{
            //    userUID = playUserUID.Value;
            //}
            //通过ViewBag 把播放账号UID 传到前端
            ViewBag.PlayUserUID = playUserUID;

            return View("Index", currentVM);
        }

        /// <summary>
        /// 唯一的用途测试程式是否OK，如果在发布肯定会超时
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult IsHealth()
        {
            var resultModel = new ApiResultModel() { isSuccess = true };
            return Content(JsonConvert.SerializeObject(resultModel), "application/json"); ;
        }

        private ApiResultModel SignInWithoutPassword(int uid)
        {
            //LoginUserMoel loginUser = new LoginUserMoel() { UserName = userName };
            HttpResponseMessage responMessage;
            var apiPath = ConfigurationManager.AppSettings["WebApiPath"].ToString();
            //var content = new StringContent(JsonConvert.SerializeObject(loginUser));
            //content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            //var contentString = JsonConvert.SerializeObject(new {uid=uid });
            //var content = new StringContent(contentString);

            //var content = new StringContent(JsonConvert.SerializeObject(new { uid = uid }));
            //content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            //responMessage = client.PostAsync(apiPath + "Login/LoginInWithoutPassword", content).Result;

            var json = JsonConvert.SerializeObject(new { uid = uid });
            var apiInsertMachineDUrl = string.Format("Login/LoginInWithoutPassword?uid={0}&roleID={1}", uid, "PlayBoardPlayUser");
            responMessage = APIHelper.APIGetAsync(apiInsertMachineDUrl);

            var jsonResult = responMessage.Content.ReadAsStringAsync().Result;
            
            var resultModel = JsonConvert.DeserializeObject<ApiResultModel>(jsonResult);
            
            if (resultModel.isSuccess)
            {
                var user = JsonConvert.DeserializeObject<AuthorizedLoginUser>(JsonConvert.SerializeObject(resultModel.data));
                //var user = JsonConvert.DeserializeObject<AuthorizedLoginUser>(responMessage.Content.ReadAsStringAsync().Result);

                if (Request.Cookies[SessionConstants.LoginTicket] != null)
                {
                    CookiesHelper.RemoveCookiesByCookieskey(Request, Response, SessionConstants.LoginTicket);
                    CookiesHelper.RemoveCookiesByCookieskey(Request, Response, SessionConstants.CurrentAccountUID);
                    CookiesHelper.RemoveCookiesByCookieskey(Request, Response, SessionConstants.CurrentUserName);
                }
                else
                {
                    CookiesHelper.AddCookies(Response, SessionConstants.LoginTicket, user.Token, 1);
                    CookiesHelper.AddCookies(Response, SessionConstants.CurrentAccountUID, user.Account_UID.ToString(), 1);
                    CookiesHelper.AddCookies(Response, SessionConstants.CurrentUserName, user.User_Name, 1);
                }


                if (Request.Cookies["APIPath"] == null)
                {
                    CookiesHelper.AddCookies(Response, "APIPath", apiPath, 1);
                }

                FormsAuthentication.SetAuthCookie(user.User_Name, false);

                SetLogon(user);
            }
            return resultModel;
        }

        private void SetLogon(AuthorizedLoginUser user)
        {
            Session[SessionConstants.LoginTicket] = user.Token;
            Session[SessionConstants.CurrentAccountUID] = user.Account_UID.ToString();
            Session[SessionConstants.CurrentUserName] = user.User_Name;
            Session[SessionConstants.CurrentLanguageId] = user.System_Language_UID.ToString();

            // Session[SessionConstants.CurrentUserInfo] = AAresult;
            if (user.USER_Ntid.ToUpper() != "EQPUSER")
            {
                var userApiUrl = string.Format("Common/GetUserInfo/?uid={0}", user.Account_UID);
                var AAresponMessage = APIHelper.APIGetAsync(userApiUrl);
                var AAresult = JsonConvert.DeserializeObject<CustomUserInfoVM>(AAresponMessage.Content.ReadAsStringAsync().Result);

                Session[SessionConstants.CurrentUserInfo] = AAresult;
                string apiUrl = string.Format("Common/GetLanguagesAPI?Language_UID={0}", user.System_Language_UID);
                var responMessage = APIHelper.APIGetAsync(apiUrl);
                var result = responMessage.Content.ReadAsStringAsync().Result;
                var languageVM = JsonConvert.DeserializeObject<LanguageVM>(result);

                string userUrl = string.Format("Common/GetUserInfo/?uid={0}", user.Account_UID);
                var userResponMessage = APIHelper.APIGetAsync(userUrl);
                var userResult = userResponMessage.Content.ReadAsStringAsync().Result;

                var userDTO = JsonConvert.DeserializeObject<CustomUserInfoVM>(userResult);

                PISSessionContext.Current.CurrentWorkingLanguage = languageVM.CurrentLanguage;
                PISSessionContext.Current.CurrentUser = userDTO;
                PISSessionContext.Current.Languages = languageVM.Languages;
                var userCookie = new HttpCookie(SessionConstants.UserSelect);
                userCookie[SessionConstants.CurrentAccountUID] = PISSessionContext.Current.CurrentUser.Account_UID.ToString();
                userCookie[SessionConstants.CurrentLanguageId] = PISSessionContext.Current.CurrentWorkingLanguage.System_Language_UID.ToString();
                userCookie.Expires.AddDays(365);
                HttpContext.Response.SetCookie(userCookie);

                //用于传值给前台JS
                Session[SessionConstants.CurrentLanguageId] = languageVM.CurrentLanguage.System_Language_UID;

            }
            else
            {
                var customUserInfoVM = new CustomUserInfoVM()
                {
                    Account_UID = user.Account_UID,
                    Language_UID = 2,
                    User_NTID = user.USER_Ntid,
                    User_Name = user.User_Name,
                    MH_Flag = user.MH_Flag,
                    LoginToken = user.Token

                };
                Session[SessionConstants.CurrentUserInfo] = customUserInfoVM;
                string apiUrl = string.Format("Common/GetLanguagesAPI?Language_UID={0}", 2);
                var responMessage = APIHelper.APIGetAsync(apiUrl);
                var result = responMessage.Content.ReadAsStringAsync().Result;
                var languageVM = JsonConvert.DeserializeObject<LanguageVM>(result);
                PISSessionContext.Current.CurrentWorkingLanguage = languageVM.CurrentLanguage;
                PISSessionContext.Current.Languages = languageVM.Languages;
                //用于传值给前台JS
                Session[SessionConstants.CurrentLanguageId] = 2;

                // JsonConvert.DeserializeObject<CustomUserInfoVM>(customUserInfoVM)
            }
        }

        /// <summary>
        /// 通过Cookie 自动登录
        /// </summary>
        /// <returns></returns>
        public ActionResult IndexWithCookie()
        {
            //先判断是否有cookie，有cookie直接转到播放页面，无cookie，直接转换到index页面

PDMS.Web/Views/PlayBoard/EBoardShow.cshtml
<div id="div-eboardshow" style="width:100%;height:100px;">
    <iframe id="iframe-eboardshow" style="width:100%;height:100%;"></iframe>
</div>

<script>
    debugger;
    //浏览器高度
    document.getElementById('div-eboardshow').style.height = $(window).height() + "px";

    //默认2秒
    PLAYTIME = 2;

    //html编码解码函数
    var HtmlUtil = {
        /*1.用正则表达式实现html转码*/
        htmlEncodeByRegExp: function (str) {
            var s = "";
            if (str.length == 0) return "";
            s = str.replace(/&/g, "&amp;");
            s = s.replace(/</g, "&lt;");
            s = s.replace(/>/g, "&gt;");
            s = s.replace(/ /g, "&nbsp;");
            s = s.replace(/\'/g, "&#39;");
            s = s.replace(/\"/g, "&quot;");
            return s;
        },
        /*2.用正则表达式实现html解码*/
        htmlDecodeByRegExp: function (str) {
            var s = "";
            if (str.length == 0) return "";
            s = str.replace(/&amp;/g, "&");
            s = s.replace(/&lt;/g, "<");
            s = s.replace(/&gt;/g, ">");
            s = s.replace(/&nbsp;/g, " ");
            s = s.replace(/&#39;/g, "\'");
            s = s.replace(/&quot;/g, "\"");
            return s;
        }
    };

    $(function () {
        debugger;
        var x = '@ViewBag.JsonParameter';
        var data = HtmlUtil.htmlDecodeByRegExp('@ViewBag.JsonParameter');

        var src = data;
        //空格换成%20
        var url = src.replace(' ','%20');
        $("#iframe-eboardshow").attr('src', url);
    });

</script>

PDMS.Web/Views/PlayBoard/ORTSHow.cshtml
<h2>ORTShow</h2>

PDMS.Web/Views/PlayBoard/PPTShow.cshtml
<div>
    <div id="ppt-html" hidden>

    </div>
</div>

<script>
    //默认2秒
    PPTSHOW_PLAYTIME = 2;
    //播放间隔常量
    PPTSHOW_PLAYINTERVAL = -1;
    //播放的文件名
    PPTSHOW_PLAYFILENAME = "";

    //html编码解码函数
    var HtmlUtil = {
        /*1.用正则表达式实现html转码*/
        htmlEncodeByRegExp: function (str) {
            var s = "";
            if (str.length == 0) return "";
            s = str.replace(/&/g, "&amp;");
            s = s.replace(/</g, "&lt;");
            s = s.replace(/>/g, "&gt;");
            s = s.replace(/ /g, "&nbsp;");
            s = s.replace(/\'/g, "&#39;");
            s = s.replace(/\"/g, "&quot;");
            return s;
        },
        /*2.用正则表达式实现html解码*/
        htmlDecodeByRegExp: function (str) {
            var s = "";
            if (str.length == 0) return "";
            s = str.replace(/&amp;/g, "&");
            s = s.replace(/&lt;/g, "<");
            s = s.replace(/&gt;/g, ">");
            s = s.replace(/&nbsp;/g, " ");
            s = s.replace(/&#39;/g, "\'");
            s = s.replace(/&quot;/g, "\"");
            return s;
        }
    };

    $(function () {
        //加载html 文件
        function loadHtmlFile(file) {
            //拼接html 文件名
            var fileName = file.substring(0, file.lastIndexOf('.pptx'));
            fileName += '.html';
            var src = '\\PIS_M\\Upload\\PlayBoard\\PPT\\' + '@ViewBag.Play_UID' + '\\' + fileName + '?time=' + new Date().getTime();    //加time 是为了不取到缓存数据
            //空格换成%20
            var url = src.replace(' ','%20');
            $("#ppt-html").load(url);

            debugger;
            //设置样式, svg 原本是 width="10in"
            $(".slide svg").attr("width", "100%");
        }

        //----------------------初始化begin----------------------
        var data = $.parseJSON(HtmlUtil.htmlDecodeByRegExp('@ViewBag.JsonParameter'));

        PPTSHOW_PLAYTIME = parseInt(data.sheetPlayTime);
        if (PPTSHOW_PLAYTIME <= 0) {
            PPTSHOW_PLAYTIME = 2;
        }

        //加载html 文件
        PPTSHOW_PLAYFILENAME = data.fileName;
        loadHtmlFile(PPTSHOW_PLAYFILENAME);

        //先显示第一个
        var slideList = $(".slide");
        slideShow = $(slideList[0]);
        var slideSiblings = slideShow.siblings();
        $(slideSiblings).hide();
        $("#ppt-html").show();
        //----------------------初始化end-----------------

        //轮播
        function setPlayInterval() {
            if (PPTSHOW_PLAYINTERVAL == -1) {
                PPTSHOW_PLAYINTERVAL = setInterval(function () {
                    slideShow = slideShow.next();

                    //最后一个播放完成，从第一个重新播放
                    if (slideShow[0] == undefined) {
                        loadHtmlFile(PPTSHOW_PLAYFILENAME);
                        var slideList = $(".slide");
                        slideShow = $(slideList[0]);
                    }
                    var slideSiblings = slideShow.siblings();
                    slideSiblings.hide();
                    slideShow.show();

                    //更新PPTSHOW_PLAYTIME，当sheetPlayTime 有变化及时更新播放切换时间
                    $.post("/PIS_M/PlayBoard/QueryPlayBoardSetting", { id: @ViewBag.SettingID }, function (data) {
                        if (data.isSuccess) {
                            var playInfo =$.parseJSON(HtmlUtil.htmlDecodeByRegExp(data.data.JsonParameter));
                            var newsheetPlayTime = parseInt(playInfo.sheetPlayTime);
                            //更新切换时间
                            if (newsheetPlayTime != PPTSHOW_PLAYTIME) {
                                PPTSHOW_PLAYTIME = newsheetPlayTime;
                                if (PPTSHOW_PLAYTIME <= 0) {
                                    PPTSHOW_PLAYTIME = 2;
                                }

                                //清空播放间隔后再次调用
                                clearInterval(PPTSHOW_PLAYINTERVAL);
                                PPTSHOW_PLAYINTERVAL = -1;
                                setPlayInterval();
                            }
                            //更新播放的html 文件
                            if (PPTSHOW_PLAYFILENAME != playInfo.fileName) {
                                PPTSHOW_PLAYFILENAME = playInfo.fileName;
                            }
                        }
                        else {
                            //播放过程中不提示错误信息
                            //PDMS.Utility.MessageBox.error(data.message);
                        }
                    });

                }, PPTSHOW_PLAYTIME * 1000);

            }
        }

        setPlayInterval();
    });

</script>

PDMS.Web/Views/PlayBoard/PictureShow.cshtml
<div style="text-align: center;">
        <img id="js-picture-img" style="margin: 0 auto;max-width:100%; max-height:100%" alt="未设置播放图片" />
</div>

<script>
    debugger;
    $(function () {
        var imgsrc = '@ViewBag.JsonParameter';
        if (imgsrc != '') {
            $("#js-picture-img").attr("src", "/PIS_M/Upload/PlayBoard/Picture/@ViewBag.Play_UID/@ViewBag.JsonParameter");
        }
    });
</script>

PDMS.Web/Views/PlayBoard/VideoShow.cshtml
@*@model int*@

<div style="text-align: center;">
    <video id="example_video_1" class="video-js vjs-default-skin vjs-big-play-centered" controls preload="none" width="640" height="264"
           x5-video-player-fullscreen="true"
           data-setup="{}">
    </video>
</div>
<link href="~/Content/css/video-js.min.css" rel="stylesheet" />
<script src="~/Scripts/plugins/video.min.js"></script>
<script>
    //记录当前播放视频
    var currentVideoName = '';

    //所有视频名称
    var allVideos = [];

    //获取视频资源接口
    var url ='@Url.Action("GetVideos", "PlayBoard")';

    var srcPath = '/PIS_M/Upload/PlayBoard/Video/@ViewBag.Play_UID/';

    $(function () {
        //获取播放资源
        //var sourceList = getRedioSource();

        ////从第一个视频开始播放
        //if (sourceList.length > 0) {
        //    currentVideoName = sourceList[0];
        //}
        
        //初始化
        var player = videojs('example_video_1', {
            autoplay: true,
            muted: false,
            controls: true,
            height: $(window).height() + $('#div-operation').height(),
            width: $(window).width(),
            loop: false,
            preload: true,
            isFullscreen: true,
            sources: [{ src: srcPath + currentVideoName, type: 'video/mp4' }]
        }, function() {
            debugger;
            playNext(this);
            //$('.vjs-fullscreen-control').click();
            //一次播放结束后，循环播放
            this.on('ended', function () {
                debugger;
                playNext(this);
            });
        });
    });

    //获取播放资源
    function getRedioSource() {
        var result;
        var settingID = @ViewBag.SettingID;
        //获取所有播放视频
        var url ='@Url.Action("GetVideos", "PlayBoard")';
        $.get(url, { settingID: settingID }, function (data) {
            result = data;
        });
        return result;
    }

    function playNext(player) {
        var nextVideoName = getNext();

        //视频不为空才播放
        if (nextVideoName != '') {
            player.src({ src: srcPath + nextVideoName, type: 'video/mp4' });
            //setTimeout(function(){ 
            //    debugger;
            //    player.play(); 
            //}, 100);
            
            debugger;
            //player.load();
        }
    }

    //视频轮流播放
    function getNext() {
        var sourceList = getRedioSource();
        if (sourceList.length == 0) {
            currentVideoName = '';
        }
        else{
            if (currentVideoName == '') {
                currentVideoName = sourceList[0];
            }else {
                //获取当前播放视频在list 中的索引
                var index = $.inArray(currentVideoName, sourceList);
                if (index < 0) {
                    //列表中没有此视频，下一个视频从第0个开始
                    currentVideoName = sourceList[0];
                }else {
                    //下一个视频索引即index + 1
                    var newIndex = (index + 1) % sourceList.length;
                    currentVideoName = sourceList[newIndex];
                }
            }
        }
        return currentVideoName;
    }


</script>